services:
  postgres-java:
    image: postgres:16-alpine
    container_name: events-api
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: events-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_event:/var/lib/postgresql/data

volumes:
  postgres_data_event:
