spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/events-db
spring.datasource.username=admin
spring.datasource.password=admin
api.security.token.secret=${JWT_SECRET:fd21e6231e9203330e131277ce8e6cc540af4e25ada27266f89b60409c4a3c45}